/*
 * The MIT License
 *
 * Copyright 2023 adfcf.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.edu.wiedza.gui;

import br.edu.wiedza.db.dao.CourseDao;
import br.edu.wiedza.db.dao.SubjectDao;
import br.edu.wiedza.entities.classroom.Course;
import br.edu.wiedza.entities.classroom.Subject;
import br.edu.wiedza.entities.persons.Employee;
import br.edu.wiedza.gui.forms.CourseForm;
import br.edu.wiedza.gui.forms.SubjectForm;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author adfcf
 */
public class CoordenationFrame extends javax.swing.JFrame {

    /**
     * Creates new form CoordenationFrame
     */
    private List<Subject> allSubjects;
    private List<Course> allCourses;

    public CoordenationFrame(Employee user) {
        initComponents();
        lblName.setText(user.getName());
        allCourses = CourseDao.getInstance().retrieveAll();
        setLocationRelativeTo(null);
        

        updateEntities();
    }

    private void updateEntities() {
        
     
        listSubjects.setModel(new DefaultListModel<>());
        allSubjects = SubjectDao.getInstance().retrieveAll();

        final var s1 = new DefaultListModel<String>();
        for (int i = 0; i < allSubjects.size(); ++i) {
            s1.add(i, allSubjects.get(i).getCode());
        }
        allCourses = CourseDao.getInstance().retrieveAll();
        listCourses.setModel(new DefaultListModel<>());

        final var s2 = new DefaultListModel<String>();
        for (int i = 0; i < allCourses.size(); ++i) {
            s2.add(i, allCourses.get(i).getSubject().getCode());
        }

        listSubjects.setModel(s1);
        listCourses.setModel(s2);
         btnReportCourses.setEnabled(true);
         btnReportSubject.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCourseYear = new javax.swing.ButtonGroup();
        tPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCourses = new javax.swing.JList<>();
        btnNewCourse = new javax.swing.JButton();
        btnViewCourse = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnReportCourses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSubjects = new javax.swing.JList<>();
        btnNewSubject = new javax.swing.JButton();
        btnViewSubject = new javax.swing.JButton();
        btnEditSubject = new javax.swing.JButton();
        btnReportSubject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listCourses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listCourses);

        btnNewCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNewCourse.setText("Cadastrar");
        btnNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCourseActionPerformed(evt);
            }
        });

        btnViewCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewCourse.setText("Visualizar");
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        btnEditCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditCourse.setText("Editar");
        btnEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCourseActionPerformed(evt);
            }
        });

        btnReportCourses.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnReportCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconReport.png"))); // NOI18N
        btnReportCourses.setText("<html> <p>Relatório  <br>Ofertas </p>   <html>");
        btnReportCourses.setEnabled(false);
        btnReportCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportCoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnViewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportCourses))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNewCourse)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewCourse)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditCourse)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tPane.addTab("Ofertas", jPanel4);

        listSubjects.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listSubjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSubjects.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSubjectsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listSubjects);

        btnNewSubject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNewSubject.setText("Cadastrar");
        btnNewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSubjectActionPerformed(evt);
            }
        });

        btnViewSubject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewSubject.setText("Visualizar");
        btnViewSubject.setEnabled(false);
        btnViewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSubjectActionPerformed(evt);
            }
        });

        btnEditSubject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditSubject.setText("Editar");
        btnEditSubject.setEnabled(false);
        btnEditSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSubjectActionPerformed(evt);
            }
        });

        btnReportSubject.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnReportSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconReport.png"))); // NOI18N
        btnReportSubject.setText("<html> <p>Relatório  <br>Disciplinas </p>   <html>");
        btnReportSubject.setEnabled(false);
        btnReportSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNewSubject)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewSubject)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditSubject)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tPane.addTab("Disciplinas", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bem vindo(a),");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("-");

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExit.setText("Sair");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPane, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(tPane, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName)
                    .addComponent(btnExit))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listSubjectsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSubjectsValueChanged

        btnViewSubject.setEnabled(true);
        btnNewSubject.setEnabled(true);
        btnEditSubject.setEnabled(true);
    }//GEN-LAST:event_listSubjectsValueChanged

    Subject findSubjetcByCode(String Code) {
        for (int i = 0; i < allSubjects.size(); ++i) {
            if (Code.equals(allSubjects.get(i).getCode().intern())) {
                return allSubjects.get(i);
            }
        }
        return null;
    }

    private Course getSelectedCourse() {
        String subject = listCourses.getSelectedValue();
        System.out.println(subject);
        for (int i = 0; i < allCourses.size(); ++i) {
            if (subject.equals(allCourses.get(i).getSubject().getCode().intern())) {
                System.out.println(allCourses.get(i).getSubject().getCode());
                return allCourses.get(i);
            }
        }
        return null;
    }

    private Subject getSelectedSubject() {
        String code = listSubjects.getSelectedValue();
        return findSubjetcByCode(code);
    }


    private void btnNewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSubjectActionPerformed

        final var form = new SubjectForm(null, false, allSubjects);
        form.setVisible(true);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                updateEntities();
            }
        });

    }//GEN-LAST:event_btnNewSubjectActionPerformed

    private void btnViewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSubjectActionPerformed
        Subject s = getSelectedSubject();
        new SubjectForm(s, true, allSubjects).setVisible(true);
    }//GEN-LAST:event_btnViewSubjectActionPerformed

    private void btnEditSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSubjectActionPerformed
        Subject s = getSelectedSubject();
        final var form = new SubjectForm(s, false, allSubjects);
        form.setVisible(true);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                updateEntities();
            }
        });
    }//GEN-LAST:event_btnEditSubjectActionPerformed

    private void btnNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCourseActionPerformed

        final var form = new CourseForm(null, false, allSubjects);
        form.setVisible(true);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                updateEntities();
            }
        });
    }//GEN-LAST:event_btnNewCourseActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        Course e = getSelectedCourse();
        final var form = new CourseForm(e, true, allSubjects);
        form.setVisible(true);
    }//GEN-LAST:event_btnViewCourseActionPerformed

    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCourseActionPerformed
        Course e = getSelectedCourse();
        final var form = new CourseForm(e, false, allSubjects);
        form.setVisible(true);
        form.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                updateEntities();
            }
        });
    }//GEN-LAST:event_btnEditCourseActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        lf.start();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnReportSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportSubjectActionPerformed

    private void btnReportCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportCoursesActionPerformed
    private void setCourseListByYear(int year) {
        final var s2 = new DefaultListModel<String>();
        for (int i = 0; i < allCourses.size(); ++i) {
            if (allCourses.get(i).getYear() == year) {
                s2.add(i, allCourses.get(i).getSubject().getCode());
            }
        }
        listCourses.setModel(s2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnEditSubject;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewCourse;
    private javax.swing.JButton btnNewSubject;
    private javax.swing.JButton btnReportCourses;
    private javax.swing.JButton btnReportSubject;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JButton btnViewSubject;
    private javax.swing.ButtonGroup groupCourseYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JList<String> listCourses;
    private javax.swing.JList<String> listSubjects;
    private javax.swing.JTabbedPane tPane;
    // End of variables declaration//GEN-END:variables
}
